export const mockStores = [
  {
    id: "1",
    name: "Fashion Boutique",
    slug: "fashion-boutique",
    description: "Trendy fashion items for all seasons",
    logo_url: "/placeholder.svg?height=100&width=100",
    banner_url: "/placeholder.svg?height=400&width=800",
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Tech Gadgets",
    slug: "tech-gadgets",
    description: "Latest tech gadgets and accessories",
    logo_url: "/placeholder.svg?height=100&width=100",
    banner_url: "/placeholder.svg?height=400&width=800",
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Home Decor",
    slug: "home-decor",
    description: "Beautiful home decoration items",
    logo_url: "/placeholder.svg?height=100&width=100",
    banner_url: "/placeholder.svg?height=400&width=800",
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Organic Foods",
    slug: "organic-foods",
    description: "Fresh and organic food products",
    logo_url: "/placeholder.svg?height=100&width=100",
    banner_url: "/placeholder.svg?height=400&width=800",
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Sports Gear",
    slug: "sports-gear",
    description: "Quality sports equipment and apparel",
    logo_url: "/placeholder.svg?height=100&width=100",
    banner_url: "/placeholder.svg?height=400&width=800",
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Handmade Crafts",
    slug: "handmade-crafts",
    description: "Unique handcrafted items and gifts",
    logo_url: "/placeholder.svg?height=100&width=100",
    banner_url: "/placeholder.svg?height=400&width=800",
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockCategories = [
  {
    id: "1",
    store_id: "1",
    name: "Men's Clothing",
    description: "Clothing items for men",
    image_url: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "2",
    store_id: "1",
    name: "Women's Clothing",
    description: "Clothing items for women",
    image_url: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "3",
    store_id: "2",
    name: "Smartphones",
    description: "Latest smartphones",
    image_url: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "4",
    store_id: "2",
    name: "Laptops",
    description: "High-performance laptops",
    image_url: "/placeholder.svg?height=200&width=200",
  },
]

export const mockProducts = [
  {
    id: "1",
    store_id: "1",
    category_id: "1",
    name: "Men's Casual T-Shirt",
    description: "Comfortable cotton t-shirt for everyday wear",
    price: 29.99,
    compare_at_price: 39.99,
    inventory_quantity: 100,
    is_published: true,
    images: [
      {
        id: "1",
        url: "/placeholder.svg?height=300&width=300",
        alt_text: "Front view of men's t-shirt",
      },
      {
        id: "2",
        url: "/placeholder.svg?height=300&width=300",
        alt_text: "Back view of men's t-shirt",
      },
    ],
  },
  {
    id: "2",
    store_id: "1",
    category_id: "2",
    name: "Women's Summer Dress",
    description: "Light and flowy summer dress",
    price: 49.99,
    compare_at_price: 69.99,
    inventory_quantity: 50,
    is_published: true,
    images: [
      {
        id: "3",
        url: "/placeholder.svg?height=300&width=300",
        alt_text: "Front view of women's dress",
      },
    ],
  },
  {
    id: "3",
    store_id: "2",
    category_id: "3",
    name: "Smartphone X",
    description: "Latest smartphone with advanced features",
    price: 899.99,
    compare_at_price: 999.99,
    inventory_quantity: 30,
    is_published: true,
    images: [
      {
        id: "4",
        url: "/placeholder.svg?height=300&width=300",
        alt_text: "Smartphone X front view",
      },
      {
        id: "5",
        url: "/placeholder.svg?height=300&width=300",
        alt_text: "Smartphone X back view",
      },
    ],
  },
  {
    id: "4",
    store_id: "2",
    category_id: "4",
    name: "Ultrabook Pro",
    description: "Thin and powerful laptop for professionals",
    price: 1299.99,
    compare_at_price: 1499.99,
    inventory_quantity: 15,
    is_published: true,
    images: [
      {
        id: "6",
        url: "/placeholder.svg?height=300&width=300",
        alt_text: "Ultrabook Pro front view",
      },
    ],
  },
]
