export const VARIANT_CATEGORIES = [
  "Clothing",
  "Fashion",
  "Apparel",
  "Shoes",
  "Footwear",
  "Accessories",
  "Jewelry",
  "Bags",
  "Sportswear",
  "Underwear",
  "Swimwear",
  "Fragrance",
  "PersonalCare",
  "Cosmetics",
  "Beauty",
];

export const categories = [
  "Electronics",
  "Clothing",
  "Fashion",
  "Apparel",
  "Shoes",
  "Accessories",
  "Home & Garden",
  "Sports & Outdoors",
  "Sportswear",
  "Books",
  "Health & Beauty",
  "Toys & Games",
  "Automotive",
  "Food & Beverages",
  "Jewelry",
  "Bags",
  "Underwear",
  "Swimwear",
  "Fragrance",
  "PersonalCare",
  "Cosmetics",
  "Beauty",
  "Other",
];
